### PR TITLE
DhcpServerOptionValue: Applies -Force switch to all Set-DhcpServerV4OptionValue calls in DhcpServerDsc.OptionValueHelper.psm1

### LINKED ISSUE #56: DhcpServerOptionValue: DNS Option Fails due to no 'Force' attribute
#### Details of the scenario you tried and the problem that is occurring
When using the DhcpServerOptionValue resource to install DNS servers for the whole DHCP server, it fails when the DNS servers are not resolvable. 

Just as when installing DNS servers via the GUI, it checks for the IP addresses to be resolvable. But due to different test scenarios or other scenarios where the DNS servers wouldn't be accessible, it fails when it cannot resolve the IP's. 

#### Verbose logs showing the problem

PowerShell Cmdlet failed: 10.1.1.1 is not a valid DNS server.
           + CategoryInfo          : InvalidArgument: (ZADHCP003:) [], CimException
           + FullyQualifiedErrorId : WIN32 87,Set-DhcpServerv4OptionValue
           + PSComputerName        : localhost

       The PowerShell DSC resource '[DhcpServerOptionValue]DirectResourceAccess' with SourceInfo '' threw one or more
       non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel
       called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
           + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
           + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
           + PSComputerName        : localhost

#### Suggested solution to the issue
Add an optional -Force setting to allow for forcing the setting when the option isn't valid at this time.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
configuration Sample_DhcpServerOptionValue_SetOption
{
    Import-DscResource -module xDHCpServer
    DhcpServerOptionValue DNSSettings
{
        Ensure = 'Present'
        OptionId = 6
        Value = '10.1.1.1', '10.2.2.2', '10.3.3.3'
        VendorClass = ''
        AddressFamily = 'IPv4'
        UserClass = ''
    }
}
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2665.amd64fre.rs1_release.181203-1755
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
PSVersion                      5.1.14393.2636
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2636
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.0.0.0

### PR DESCRIPTION
**Pull request by realslacker**
#### Pull Request (PR) description
The calls to Set-DhcpServerV4OptionValue fail if the internal validation for some options fail. We should apply all changes in a DSC configuration as they are written and not fail on unnecessary validation. 

#### This Pull Request (PR) fixes the following issues
- Fixes #56 
#### Task list

Note: This change will not affect any of the currently written DSC code, as such none of the documentation should need to be updated.

- [X] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xdhcpserver/78)

### CODE REVIEW

**Comment by johlju** [comment]
I think we should make the Force parameter optional by adding the a new parameter Force to the resource. If set we pass Force to the commands.

**Comment by johlju** [comment]
Need help verifying that using `-Force` actually works, as per https://github.com/dsccommunity/xDhcpServer/issues/56#issuecomment-1119816710 it should only be applicable when using `DnsServer` parameter. 🤔

**Comment by realslacker** [comment]
@johlju it's been a while since I submitted this pull request, but at the time I used this code to push some changes. I would be happy to do some additional testing but it will take me a bit to get a test environment setup.

**Comment by johlju** [comment]
Would be great if you have the time, thank you 😊

**Comment by jangins101** [comment]
since I ran into this issue again myself (#56 ), wanted to bring it back up for review. I added a comment on the issue (#56) before, and have not seen any problems with with the -Force parameter being added in my environments.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xdhcpserver/78#-:-Nc6Sxnf3J8tt_y8yI5u:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @realslacker)

**Pull request merged**
