### PR TITLE
New resources DhcpServerExclusionRange, DhcpServerBinding

### LINKED ISSUE #7: Feature Request - Exclusion Range
Hi Team, please can you kindly add the ability to add/remove DHCP exclusion ranges. 

Example below; At the moment only Method 1 is available.

Say for instance Network Devices/Servers sit on 192.168.1.1 to 192.168.1.20

Method 1: Scope 192.168.1.21 -> 192.168.1.254

Method 2: Scope 192.168.1.1 -> 192.168.1.254
                 Reservation 192.168.1.1 -> 192.168.1.20

Many organizations use Method 2 as best practice for defining DHCP scopes.

DHCP cmdlets to accomplish this;

Get-DhcpServerv4ExclusionRange
Add-DhcpServerv4ExclusionRange
Remove-DhcpServerv4ExclusionRange

### LINKED ISSUE #55: DhcpServerBinding: New resource proposal
### Description
Resource to control the behavior of Dhcp server NIC bindings. By default all nics are bound to the dhcp service but this is not always the desired state.

### Proposed properties
InterfaceAlias, Ensure
### Special considerations or limitations
n/a

### PR DESCRIPTION
**Pull request by aromano2**
#### Pull Request (PR) description
Adding DhcpServerExclusionRange resource. Allows you to define an exclusion range for a specific scope. Also added DhcpServerBinding resource which allows you to control the behavior or network bindings within Dhcp.

#### This Pull Request (PR) fixes the following issues
Fixes #7
Fixes #55

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xdhcpserver/54)

### CODE REVIEW

**Comment by aromano2** [comment]
@johlju can anyone review this PR please?

**Comment by esincic** [comment]
Can anyone review this PR, please? Exclusions and bindings are very welcome in this cookbook.

**Comment by johlju** [comment]
I have a lot of PRs to review in my backlog but when I can I will help with the review in this one. But it will take a while. :/

If someone else would want to help out to review this one then please do, if there are any questions I’m happy to give pointers.

**Comment by cwegener** [comment]
These two resources would be great additions indeed.

Apart from performing code review, do the failed CI test need to be resolved as well before merging?

**Comment by johlju** [comment]
Yes, all tests need to pass for it to be merged.

**Comment by aromano2** [comment]
@cwegener @johlju fixed the test, thanks!

**Comment by johlju** [comment]
@aromano2 I will review this one as soon as I have time. It gets labelled abandoned because it is not labelled 'needs review' and I can label it. 
But I have this on the todo list to review!

/cc @gaelcolas when you have permission, could you please label this one?

**Comment by gaelcolas** [comment]
Labelled and turned off the stale bot.
I'm going through the Abandoned PR, and will try to come back to review this one. Bear with us!

**Comment by johlju** [comment]
THis repo was converted to the new CI pipeline. I pushed changes to this PR so that the PR is up-to-date with those changes, and so that the PR is passing HQRM and unit testing.

**Comment by johlju** [comment]
Merging this to get this one through.

**Pull request merged**
